// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEntry = `-- name: CreateAuditEntry :exec

INSERT INTO audit_log (tenant_id, actor_id, command, outcome, detail, trace_id, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAuditEntryParams struct {
	TenantID   pgtype.UUID
	ActorID    string
	Command    string
	Outcome    string
	Detail     string
	TraceID    string
	OccurredAt pgtype.Timestamptz
}

// Журнал аудита. Только INSERT: журнал append-only, что закреплено
// и на уровне БД — RLS-политик UPDATE/DELETE у таблицы нет.
func (q *Queries) CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) error {
	_, err := q.db.Exec(ctx, createAuditEntry,
		arg.TenantID,
		arg.ActorID,
		arg.Command,
		arg.Outcome,
		arg.Detail,
		arg.TraceID,
		arg.OccurredAt,
	)
	return err
}

const listAuditEntries = `-- name: ListAuditEntries :many
SELECT id, tenant_id, actor_id, command, outcome, detail, trace_id, occurred_at FROM audit_log ORDER BY occurred_at DESC, id DESC LIMIT $1
`

func (q *Queries) ListAuditEntries(ctx context.Context, limit int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEntries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.Command,
			&i.Outcome,
			&i.Detail,
			&i.TraceID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
