// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: campus.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const campusJournal = `-- name: CampusJournal :many
SELECT gr.id, gr.subject, gr.grade, gr.graded_on, gr.graded_by, gr.note,
       s.id AS student_id, s.full_name, g.code AS group_code
FROM campus_grades gr
JOIN campus_students s ON s.id = gr.student_id
LEFT JOIN campus_groups g ON g.id = s.group_id
WHERE ($2::uuid IS NULL OR s.group_id = $2)
  AND ($3::text IS NULL OR gr.subject = $3)
  AND ($4::uuid IS NULL OR s.id = $4)
ORDER BY s.full_name, gr.graded_on, gr.subject
LIMIT $1
`

type CampusJournalParams struct {
	Limit     int32
	GroupID   pgtype.UUID
	Subject   *string
	StudentID pgtype.UUID
}

type CampusJournalRow struct {
	ID        pgtype.UUID
	Subject   string
	Grade     int16
	GradedOn  pgtype.Date
	GradedBy  string
	Note      string
	StudentID pgtype.UUID
	FullName  string
	GroupCode *string
}

func (q *Queries) CampusJournal(ctx context.Context, arg CampusJournalParams) ([]CampusJournalRow, error) {
	rows, err := q.db.Query(ctx, campusJournal,
		arg.Limit,
		arg.GroupID,
		arg.Subject,
		arg.StudentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampusJournalRow
	for rows.Next() {
		var i CampusJournalRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Grade,
			&i.GradedOn,
			&i.GradedBy,
			&i.Note,
			&i.StudentID,
			&i.FullName,
			&i.GroupCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCampusGrade = `-- name: CreateCampusGrade :one
INSERT INTO campus_grades (tenant_id, student_id, subject, grade, graded_on, graded_by, note)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, tenant_id, student_id, subject, grade, graded_on, graded_by, note, created_at
`

type CreateCampusGradeParams struct {
	TenantID  pgtype.UUID
	StudentID pgtype.UUID
	Subject   string
	Grade     int16
	GradedOn  pgtype.Date
	GradedBy  string
	Note      string
}

func (q *Queries) CreateCampusGrade(ctx context.Context, arg CreateCampusGradeParams) (CampusGrade, error) {
	row := q.db.QueryRow(ctx, createCampusGrade,
		arg.TenantID,
		arg.StudentID,
		arg.Subject,
		arg.Grade,
		arg.GradedOn,
		arg.GradedBy,
		arg.Note,
	)
	var i CampusGrade
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.Subject,
		&i.Grade,
		&i.GradedOn,
		&i.GradedBy,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const createCampusGroup = `-- name: CreateCampusGroup :one

INSERT INTO campus_groups (tenant_id, code, name)
VALUES ($1, $2, $3) RETURNING id, tenant_id, code, name, created_at
`

type CreateCampusGroupParams struct {
	TenantID pgtype.UUID
	Code     string
	Name     string
}

// Запросы модуля «Кампус». Границу tenant'ов проводит RLS.
func (q *Queries) CreateCampusGroup(ctx context.Context, arg CreateCampusGroupParams) (CampusGroup, error) {
	row := q.db.QueryRow(ctx, createCampusGroup, arg.TenantID, arg.Code, arg.Name)
	var i CampusGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createCampusStudent = `-- name: CreateCampusStudent :one
INSERT INTO campus_students (tenant_id, full_name, email, group_id, status)
VALUES ($1, $2, $3, $4, $5) RETURNING id, tenant_id, full_name, email, group_id, status, created_at, search
`

type CreateCampusStudentParams struct {
	TenantID pgtype.UUID
	FullName string
	Email    string
	GroupID  pgtype.UUID
	Status   string
}

func (q *Queries) CreateCampusStudent(ctx context.Context, arg CreateCampusStudentParams) (CampusStudent, error) {
	row := q.db.QueryRow(ctx, createCampusStudent,
		arg.TenantID,
		arg.FullName,
		arg.Email,
		arg.GroupID,
		arg.Status,
	)
	var i CampusStudent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FullName,
		&i.Email,
		&i.GroupID,
		&i.Status,
		&i.CreatedAt,
		&i.Search,
	)
	return i, err
}

const getCampusStudent = `-- name: GetCampusStudent :one
SELECT id, tenant_id, full_name, email, group_id, status, created_at, search FROM campus_students WHERE id = $1
`

func (q *Queries) GetCampusStudent(ctx context.Context, id pgtype.UUID) (CampusStudent, error) {
	row := q.db.QueryRow(ctx, getCampusStudent, id)
	var i CampusStudent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FullName,
		&i.Email,
		&i.GroupID,
		&i.Status,
		&i.CreatedAt,
		&i.Search,
	)
	return i, err
}

const listCampusGroups = `-- name: ListCampusGroups :many
SELECT g.id, g.tenant_id, g.code, g.name, g.created_at, count(s.id) FILTER (WHERE s.status = 'active')::int AS active_students
FROM campus_groups g
LEFT JOIN campus_students s ON s.group_id = g.id
GROUP BY g.id
ORDER BY g.code
`

type ListCampusGroupsRow struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	Code           string
	Name           string
	CreatedAt      pgtype.Timestamptz
	ActiveStudents int32
}

func (q *Queries) ListCampusGroups(ctx context.Context) ([]ListCampusGroupsRow, error) {
	rows, err := q.db.Query(ctx, listCampusGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampusGroupsRow
	for rows.Next() {
		var i ListCampusGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.CreatedAt,
			&i.ActiveStudents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampusStudents = `-- name: ListCampusStudents :many
SELECT s.id, s.tenant_id, s.full_name, s.email, s.group_id, s.status, s.created_at, s.search, g.code AS group_code
FROM campus_students s
LEFT JOIN campus_groups g ON g.id = s.group_id
WHERE ($3::uuid IS NULL OR s.group_id = $3)
  AND ($4::text IS NULL OR s.status = $4)
  AND ($5::text IS NULL
       OR s.search @@ websearch_to_tsquery('russian', $5))
ORDER BY
  CASE WHEN $6::text = 'name'       THEN s.full_name END ASC,
  CASE WHEN $6::text = 'name_desc'  THEN s.full_name END DESC,
  CASE WHEN $6::text = 'group'      THEN g.code END ASC NULLS LAST,
  CASE WHEN $6::text = 'created'    THEN s.created_at END ASC,
  s.created_at DESC
LIMIT $1 OFFSET $2
`

type ListCampusStudentsParams struct {
	Limit   int32
	Offset  int32
	GroupID pgtype.UUID
	Status  *string
	Q       *string
	Sort    string
}

type ListCampusStudentsRow struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	FullName  string
	Email     string
	GroupID   pgtype.UUID
	Status    string
	CreatedAt pgtype.Timestamptz
	Search    interface{}
	GroupCode *string
}

func (q *Queries) ListCampusStudents(ctx context.Context, arg ListCampusStudentsParams) ([]ListCampusStudentsRow, error) {
	rows, err := q.db.Query(ctx, listCampusStudents,
		arg.Limit,
		arg.Offset,
		arg.GroupID,
		arg.Status,
		arg.Q,
		arg.Sort,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampusStudentsRow
	for rows.Next() {
		var i ListCampusStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FullName,
			&i.Email,
			&i.GroupID,
			&i.Status,
			&i.CreatedAt,
			&i.Search,
			&i.GroupCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCampusStudents = `-- name: SearchCampusStudents :many
SELECT s.id, s.full_name, s.status, g.code AS group_code,
       ts_rank(s.search, q)::real AS rank
FROM campus_students s
LEFT JOIN campus_groups g ON g.id = s.group_id,
     websearch_to_tsquery('russian', $1) q
WHERE s.search @@ q
ORDER BY rank DESC, s.full_name
LIMIT $2
`

type SearchCampusStudentsParams struct {
	WebsearchToTsquery string
	Limit              int32
}

type SearchCampusStudentsRow struct {
	ID        pgtype.UUID
	FullName  string
	Status    string
	GroupCode *string
	Rank      float32
}

func (q *Queries) SearchCampusStudents(ctx context.Context, arg SearchCampusStudentsParams) ([]SearchCampusStudentsRow, error) {
	rows, err := q.db.Query(ctx, searchCampusStudents, arg.WebsearchToTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCampusStudentsRow
	for rows.Next() {
		var i SearchCampusStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Status,
			&i.GroupCode,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampusStudent = `-- name: UpdateCampusStudent :one
UPDATE campus_students
SET full_name = $2, email = $3, group_id = $4, status = $5
WHERE id = $1
RETURNING id, tenant_id, full_name, email, group_id, status, created_at, search
`

type UpdateCampusStudentParams struct {
	ID       pgtype.UUID
	FullName string
	Email    string
	GroupID  pgtype.UUID
	Status   string
}

func (q *Queries) UpdateCampusStudent(ctx context.Context, arg UpdateCampusStudentParams) (CampusStudent, error) {
	row := q.db.QueryRow(ctx, updateCampusStudent,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.GroupID,
		arg.Status,
	)
	var i CampusStudent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FullName,
		&i.Email,
		&i.GroupID,
		&i.Status,
		&i.CreatedAt,
		&i.Search,
	)
	return i, err
}
