// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFilesBySHA = `-- name: CountFilesBySHA :one
SELECT count(*) FROM files WHERE sha256 = $1
`

func (q *Queries) CountFilesBySHA(ctx context.Context, sha256 string) (int64, error) {
	row := q.db.QueryRow(ctx, countFilesBySHA, sha256)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFile = `-- name: CreateFile :one

INSERT INTO files (tenant_id, name, content_type, size, sha256, entity_type, entity_id, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, name, content_type, size, sha256, entity_type, entity_id, uploaded_by, created_at, search
`

type CreateFileParams struct {
	TenantID    pgtype.UUID
	Name        string
	ContentType string
	Size        int64
	Sha256      string
	EntityType  string
	EntityID    string
	UploadedBy  string
}

// Запросы файлового хранилища. Границу tenant'ов проводит RLS.
func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.TenantID,
		arg.Name,
		arg.ContentType,
		arg.Size,
		arg.Sha256,
		arg.EntityType,
		arg.EntityID,
		arg.UploadedBy,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ContentType,
		&i.Size,
		&i.Sha256,
		&i.EntityType,
		&i.EntityID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.Search,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :execrows
DELETE FROM files WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFile = `-- name: GetFile :one
SELECT id, tenant_id, name, content_type, size, sha256, entity_type, entity_id, uploaded_by, created_at, search FROM files WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id pgtype.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ContentType,
		&i.Size,
		&i.Sha256,
		&i.EntityType,
		&i.EntityID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.Search,
	)
	return i, err
}

const listFiles = `-- name: ListFiles :many
SELECT id, tenant_id, name, content_type, size, sha256, entity_type, entity_id, uploaded_by, created_at, search FROM files
WHERE ($2::text IS NULL OR entity_type = $2)
  AND ($3::text IS NULL OR entity_id = $3)
ORDER BY created_at DESC, id
LIMIT $1
`

type ListFilesParams struct {
	Limit      int32
	EntityType *string
	EntityID   *string
}

func (q *Queries) ListFiles(ctx context.Context, arg ListFilesParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFiles, arg.Limit, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ContentType,
			&i.Size,
			&i.Sha256,
			&i.EntityType,
			&i.EntityID,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.Search,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFiles = `-- name: SearchFiles :many
SELECT f.id, f.name, f.content_type, f.created_at,
       ts_rank(f.search, q)::real AS rank
FROM files f, websearch_to_tsquery('russian', $1) q
WHERE f.search @@ q
ORDER BY rank DESC, f.created_at DESC
LIMIT $2
`

type SearchFilesParams struct {
	WebsearchToTsquery string
	Limit              int32
}

type SearchFilesRow struct {
	ID          pgtype.UUID
	Name        string
	ContentType string
	CreatedAt   pgtype.Timestamptz
	Rank        float32
}

func (q *Queries) SearchFiles(ctx context.Context, arg SearchFilesParams) ([]SearchFilesRow, error) {
	rows, err := q.db.Query(ctx, searchFiles, arg.WebsearchToTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchFilesRow
	for rows.Next() {
		var i SearchFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContentType,
			&i.CreatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
