// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: finance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearFinanceMonthlyTurnovers = `-- name: ClearFinanceMonthlyTurnovers :exec

DELETE FROM finance_monthly_turnovers
`

// Витрина оборотов: пересчёт «снести и перелить» в транзакции tenant'а.
func (q *Queries) ClearFinanceMonthlyTurnovers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearFinanceMonthlyTurnovers)
	return err
}

const createFinanceAccount = `-- name: CreateFinanceAccount :one

INSERT INTO finance_accounts (tenant_id, code, name, type, currency)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, code, name, type, currency, created_at, search
`

type CreateFinanceAccountParams struct {
	TenantID pgtype.UUID
	Code     string
	Name     string
	Type     string
	Currency string
}

// Запросы модуля «Финансы». Генерация: make sqlc → internal/platform/postgres/db.
// Фильтра по tenant_id в тексте запросов нет намеренно: каждый запрос
// выполняется в транзакции с app.tenant_id, и границу проводит RLS.
func (q *Queries) CreateFinanceAccount(ctx context.Context, arg CreateFinanceAccountParams) (FinanceAccount, error) {
	row := q.db.QueryRow(ctx, createFinanceAccount,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Currency,
	)
	var i FinanceAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.CreatedAt,
		&i.Search,
	)
	return i, err
}

const createFinanceEntry = `-- name: CreateFinanceEntry :one
INSERT INTO finance_entries (tenant_id, memo, posted_by)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, memo, posted_by, posted_at, search
`

type CreateFinanceEntryParams struct {
	TenantID pgtype.UUID
	Memo     string
	PostedBy string
}

func (q *Queries) CreateFinanceEntry(ctx context.Context, arg CreateFinanceEntryParams) (FinanceEntry, error) {
	row := q.db.QueryRow(ctx, createFinanceEntry, arg.TenantID, arg.Memo, arg.PostedBy)
	var i FinanceEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Memo,
		&i.PostedBy,
		&i.PostedAt,
		&i.Search,
	)
	return i, err
}

const createFinanceLine = `-- name: CreateFinanceLine :exec
INSERT INTO finance_lines (tenant_id, entry_id, account_id, side, amount)
VALUES ($1, $2, $3, $4, $5)
`

type CreateFinanceLineParams struct {
	TenantID  pgtype.UUID
	EntryID   pgtype.UUID
	AccountID pgtype.UUID
	Side      string
	Amount    int64
}

func (q *Queries) CreateFinanceLine(ctx context.Context, arg CreateFinanceLineParams) error {
	_, err := q.db.Exec(ctx, createFinanceLine,
		arg.TenantID,
		arg.EntryID,
		arg.AccountID,
		arg.Side,
		arg.Amount,
	)
	return err
}

const fillFinanceMonthlyTurnovers = `-- name: FillFinanceMonthlyTurnovers :exec
INSERT INTO finance_monthly_turnovers (tenant_id, month, account_id, debit, credit)
SELECT l.tenant_id,
       date_trunc('month', e.posted_at)::date,
       l.account_id,
       COALESCE(SUM(l.amount) FILTER (WHERE l.side = 'debit'), 0),
       COALESCE(SUM(l.amount) FILTER (WHERE l.side = 'credit'), 0)
FROM finance_lines l
JOIN finance_entries e ON e.id = l.entry_id
GROUP BY 1, 2, 3
`

func (q *Queries) FillFinanceMonthlyTurnovers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, fillFinanceMonthlyTurnovers)
	return err
}

const getFinanceAccount = `-- name: GetFinanceAccount :one
SELECT id, tenant_id, code, name, type, currency, created_at, search FROM finance_accounts WHERE id = $1
`

func (q *Queries) GetFinanceAccount(ctx context.Context, id pgtype.UUID) (FinanceAccount, error) {
	row := q.db.QueryRow(ctx, getFinanceAccount, id)
	var i FinanceAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.CreatedAt,
		&i.Search,
	)
	return i, err
}

const listFinanceAccountsByIDs = `-- name: ListFinanceAccountsByIDs :many
SELECT id, tenant_id, code, name, type, currency, created_at, search FROM finance_accounts WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListFinanceAccountsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]FinanceAccount, error) {
	rows, err := q.db.Query(ctx, listFinanceAccountsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinanceAccount
	for rows.Next() {
		var i FinanceAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.CreatedAt,
			&i.Search,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinanceAccountsWithBalances = `-- name: ListFinanceAccountsWithBalances :many
SELECT
    a.id, a.tenant_id, a.code, a.name, a.type, a.currency, a.created_at, a.search,
    COALESCE(SUM(
        CASE
            WHEN a.type IN ('asset', 'expense') AND l.side = 'debit'  THEN l.amount
            WHEN a.type IN ('asset', 'expense') AND l.side = 'credit' THEN -l.amount
            WHEN l.side = 'credit' THEN l.amount
            WHEN l.side = 'debit'  THEN -l.amount
        END
    ), 0)::bigint AS balance
FROM finance_accounts a
LEFT JOIN finance_lines l ON l.account_id = a.id
GROUP BY a.id
ORDER BY a.code
`

type ListFinanceAccountsWithBalancesRow struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	Code      string
	Name      string
	Type      string
	Currency  string
	CreatedAt pgtype.Timestamptz
	Search    interface{}
	Balance   int64
}

func (q *Queries) ListFinanceAccountsWithBalances(ctx context.Context) ([]ListFinanceAccountsWithBalancesRow, error) {
	rows, err := q.db.Query(ctx, listFinanceAccountsWithBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFinanceAccountsWithBalancesRow
	for rows.Next() {
		var i ListFinanceAccountsWithBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.CreatedAt,
			&i.Search,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinanceEntries = `-- name: ListFinanceEntries :many
SELECT id, tenant_id, memo, posted_by, posted_at, search FROM finance_entries ORDER BY posted_at, id
`

func (q *Queries) ListFinanceEntries(ctx context.Context) ([]FinanceEntry, error) {
	rows, err := q.db.Query(ctx, listFinanceEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinanceEntry
	for rows.Next() {
		var i FinanceEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Memo,
			&i.PostedBy,
			&i.PostedAt,
			&i.Search,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinanceLines = `-- name: ListFinanceLines :many
SELECT id, tenant_id, entry_id, account_id, side, amount FROM finance_lines ORDER BY entry_id, id
`

func (q *Queries) ListFinanceLines(ctx context.Context) ([]FinanceLine, error) {
	rows, err := q.db.Query(ctx, listFinanceLines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinanceLine
	for rows.Next() {
		var i FinanceLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntryID,
			&i.AccountID,
			&i.Side,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinanceMonthlyTurnovers = `-- name: ListFinanceMonthlyTurnovers :many
SELECT m.month, m.debit, m.credit, m.refreshed_at,
       a.id AS account_id, a.code, a.name
FROM finance_monthly_turnovers m
JOIN finance_accounts a ON a.id = m.account_id
ORDER BY m.month DESC, a.code
`

type ListFinanceMonthlyTurnoversRow struct {
	Month       pgtype.Date
	Debit       int64
	Credit      int64
	RefreshedAt pgtype.Timestamptz
	AccountID   pgtype.UUID
	Code        string
	Name        string
}

func (q *Queries) ListFinanceMonthlyTurnovers(ctx context.Context) ([]ListFinanceMonthlyTurnoversRow, error) {
	rows, err := q.db.Query(ctx, listFinanceMonthlyTurnovers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFinanceMonthlyTurnoversRow
	for rows.Next() {
		var i ListFinanceMonthlyTurnoversRow
		if err := rows.Scan(
			&i.Month,
			&i.Debit,
			&i.Credit,
			&i.RefreshedAt,
			&i.AccountID,
			&i.Code,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
