// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: idempotency.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys SET status = $2, content_type = $3, body = $4
WHERE key = $1
`

type CompleteIdempotencyKeyParams struct {
	Key         string
	Status      int32
	ContentType string
	Body        []byte
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.Key,
		arg.Status,
		arg.ContentType,
		arg.Body,
	)
	return err
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :exec
DELETE FROM idempotency_keys WHERE key = $1
`

func (q *Queries) DeleteIdempotencyKey(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteIdempotencyKey, key)
	return err
}

const deleteOldIdempotencyKeys = `-- name: DeleteOldIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE created_at < now() - interval '24 hours'
`

func (q *Queries) DeleteOldIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT tenant_id, key, status, content_type, body, created_at FROM idempotency_keys WHERE key = $1
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.TenantID,
		&i.Key,
		&i.Status,
		&i.ContentType,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const tryInsertIdempotencyKey = `-- name: TryInsertIdempotencyKey :execrows

INSERT INTO idempotency_keys (tenant_id, key)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type TryInsertIdempotencyKeyParams struct {
	TenantID pgtype.UUID
	Key      string
}

// Идемпотентные ключи. Все запросы — в tenant-транзакции (RLS).
func (q *Queries) TryInsertIdempotencyKey(ctx context.Context, arg TryInsertIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, tryInsertIdempotencyKey, arg.TenantID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
