// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         int64
	TenantID   pgtype.UUID
	ActorID    string
	Command    string
	Outcome    string
	Detail     string
	TraceID    string
	OccurredAt pgtype.Timestamptz
	Diff       []byte
}

type CampusGrade struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	StudentID pgtype.UUID
	Subject   string
	Grade     int16
	GradedOn  pgtype.Date
	GradedBy  string
	Note      string
	CreatedAt pgtype.Timestamptz
}

type CampusGroup struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	Code      string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type CampusStudent struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	FullName  string
	Email     string
	GroupID   pgtype.UUID
	Status    string
	CreatedAt pgtype.Timestamptz
	Search    interface{}
}

type File struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	Name        string
	ContentType string
	Size        int64
	Sha256      string
	EntityType  string
	EntityID    string
	UploadedBy  string
	CreatedAt   pgtype.Timestamptz
	Search      interface{}
}

type FinanceAccount struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	Code      string
	Name      string
	Type      string
	Currency  string
	CreatedAt pgtype.Timestamptz
	Search    interface{}
}

type FinanceEntry struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
	Memo     string
	PostedBy string
	PostedAt pgtype.Timestamptz
	Search   interface{}
}

type FinanceLine struct {
	ID        int64
	TenantID  pgtype.UUID
	EntryID   pgtype.UUID
	AccountID pgtype.UUID
	Side      string
	Amount    int64
}

type FinanceMonthlyTurnover struct {
	TenantID    pgtype.UUID
	Month       pgtype.Date
	AccountID   pgtype.UUID
	Debit       int64
	Credit      int64
	RefreshedAt pgtype.Timestamptz
}

type IdempotencyKey struct {
	TenantID    pgtype.UUID
	Key         string
	Status      int32
	ContentType string
	Body        []byte
	CreatedAt   pgtype.Timestamptz
}

type Notification struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	UserID    pgtype.UUID
	Kind      string
	Title     string
	Body      string
	RefType   string
	RefID     string
	CreatedAt pgtype.Timestamptz
	ReadAt    pgtype.Timestamptz
}

type Outbox struct {
	ID          int64
	TenantID    pgtype.UUID
	Topic       string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
	AvailableAt pgtype.Timestamptz
	Attempts    int32
	DoneAt      pgtype.Timestamptz
	LastError   string
}

type Session struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type Task struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	Title     string
	Note      string
	Status    string
	DueOn     pgtype.Date
	Assignee  string
	CreatedBy string
	CreatedAt pgtype.Timestamptz
	DoneAt    pgtype.Timestamptz
	Search    interface{}
}

type Tenant struct {
	ID        pgtype.UUID
	Slug      string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	Email        string
	PasswordHash string
	DisplayName  string
	Roles        []string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}
