// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         int64
	TenantID   pgtype.UUID
	ActorID    string
	Command    string
	Outcome    string
	Detail     string
	TraceID    string
	OccurredAt pgtype.Timestamptz
}

type File struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	Name        string
	ContentType string
	Size        int64
	Sha256      string
	EntityType  string
	EntityID    string
	UploadedBy  string
	CreatedAt   pgtype.Timestamptz
	Search      interface{}
}

type FinanceAccount struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	Code      string
	Name      string
	Type      string
	Currency  string
	CreatedAt pgtype.Timestamptz
	Search    interface{}
}

type FinanceEntry struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
	Memo     string
	PostedBy string
	PostedAt pgtype.Timestamptz
	Search   interface{}
}

type FinanceLine struct {
	ID        int64
	TenantID  pgtype.UUID
	EntryID   pgtype.UUID
	AccountID pgtype.UUID
	Side      string
	Amount    int64
}

type FinanceMonthlyTurnover struct {
	TenantID    pgtype.UUID
	Month       pgtype.Date
	AccountID   pgtype.UUID
	Debit       int64
	Credit      int64
	RefreshedAt pgtype.Timestamptz
}

type Session struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type Tenant struct {
	ID        pgtype.UUID
	Slug      string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	Email        string
	PasswordHash string
	DisplayName  string
	Roles        []string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}
