// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (tenant_id, user_id, kind, title, body, ref_type, ref_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, user_id, kind, title, body, ref_type, ref_id, created_at, read_at
`

type CreateNotificationParams struct {
	TenantID pgtype.UUID
	UserID   pgtype.UUID
	Kind     string
	Title    string
	Body     string
	RefType  string
	RefID    string
}

// Уведомления. Все запросы — в tenant-транзакции (RLS); лента и отметки
// о прочтении дополнительно ограничены user_id получателя.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.TenantID,
		arg.UserID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.RefType,
		arg.RefID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.RefType,
		&i.RefID,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, tenant_id, user_id, kind, title, body, ref_type, ref_id, created_at, read_at FROM notifications
WHERE user_id = $1
  AND (NOT $4::boolean OR read_at IS NULL)
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID     pgtype.UUID
	Limit      int32
	Offset     int32
	UnreadOnly bool
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.UnreadOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.RefType,
			&i.RefID,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications SET read_at = now()
WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
