// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buryOutbox = `-- name: BuryOutbox :exec
UPDATE outbox SET done_at = now(), last_error = $2 WHERE id = $1
`

type BuryOutboxParams struct {
	ID        int64
	LastError string
}

// Хоронит сообщение после исчерпания попыток: done_at ставится, диагноз
// остаётся — мёртвые письма ищутся по done_at IS NOT NULL AND last_error <> ”.
func (q *Queries) BuryOutbox(ctx context.Context, arg BuryOutboxParams) error {
	_, err := q.db.Exec(ctx, buryOutbox, arg.ID, arg.LastError)
	return err
}

const claimOutboxBatch = `-- name: ClaimOutboxBatch :many
UPDATE outbox SET attempts = attempts + 1,
    available_at = now() + make_interval(secs => least(3600.0, 10.0 * (2.0 ^ least(attempts, 8))))
WHERE id IN (
    SELECT id FROM outbox
    WHERE done_at IS NULL AND available_at <= now()
    ORDER BY id
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, tenant_id, topic, payload, created_at, available_at, attempts, done_at, last_error
`

// Забирает пачку готовых сообщений и сразу сдвигает available_at с
// экспоненциальным backoff: если воркер умрёт посреди обработки,
// сообщение вернётся в очередь само. SKIP LOCKED позволяет нескольким
// инстансам разбирать очередь без взаимных блокировок.
func (q *Queries) ClaimOutboxBatch(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, claimOutboxBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Topic,
			&i.Payload,
			&i.CreatedAt,
			&i.AvailableAt,
			&i.Attempts,
			&i.DoneAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOldOutbox = `-- name: DeleteOldOutbox :execrows
DELETE FROM outbox WHERE done_at IS NOT NULL AND done_at < now() - interval '30 days'
`

func (q *Queries) DeleteOldOutbox(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldOutbox)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueOutbox = `-- name: EnqueueOutbox :exec

INSERT INTO outbox (tenant_id, topic, payload, available_at)
VALUES ($1, $2, $3, now() + make_interval(secs => $4::float8))
`

type EnqueueOutboxParams struct {
	TenantID  pgtype.UUID
	Topic     string
	Payload   []byte
	DelaySecs float64
}

// Transactional outbox. Enqueue выполняется в транзакции команды
// (присоединяется через контекст); Claim/Done/Fail — воркером на пуле,
// вне tenant-транзакций (таблица без RLS).
func (q *Queries) EnqueueOutbox(ctx context.Context, arg EnqueueOutboxParams) error {
	_, err := q.db.Exec(ctx, enqueueOutbox,
		arg.TenantID,
		arg.Topic,
		arg.Payload,
		arg.DelaySecs,
	)
	return err
}

const markOutboxDone = `-- name: MarkOutboxDone :exec
UPDATE outbox SET done_at = now(), last_error = '' WHERE id = $1
`

func (q *Queries) MarkOutboxDone(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxDone, id)
	return err
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox SET last_error = $2 WHERE id = $1
`

type MarkOutboxFailedParams struct {
	ID        int64
	LastError string
}

// Фиксирует диагноз; время следующей попытки уже выставлено при Claim.
func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, arg.ID, arg.LastError)
	return err
}
