// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: search.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchFinanceAccounts = `-- name: SearchFinanceAccounts :many

SELECT a.id, a.code, a.name,
       ts_rank(a.search, q)::real AS rank
FROM finance_accounts a, websearch_to_tsquery('russian', $1) q
WHERE a.search @@ q
ORDER BY rank DESC, a.code
LIMIT $2
`

type SearchFinanceAccountsParams struct {
	WebsearchToTsquery string
	Limit              int32
}

type SearchFinanceAccountsRow struct {
	ID   pgtype.UUID
	Code string
	Name string
	Rank float32
}

// Полнотекстовый поиск (веб-синтаксис websearch_to_tsquery: кавычки,
// минус-слова, OR). Фильтра по tenant_id нет — границу проводит RLS.
func (q *Queries) SearchFinanceAccounts(ctx context.Context, arg SearchFinanceAccountsParams) ([]SearchFinanceAccountsRow, error) {
	rows, err := q.db.Query(ctx, searchFinanceAccounts, arg.WebsearchToTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchFinanceAccountsRow
	for rows.Next() {
		var i SearchFinanceAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFinanceEntries = `-- name: SearchFinanceEntries :many
SELECT e.id, e.memo, e.posted_at,
       ts_rank(e.search, q)::real AS rank
FROM finance_entries e, websearch_to_tsquery('russian', $1) q
WHERE e.search @@ q
ORDER BY rank DESC, e.posted_at DESC
LIMIT $2
`

type SearchFinanceEntriesParams struct {
	WebsearchToTsquery string
	Limit              int32
}

type SearchFinanceEntriesRow struct {
	ID       pgtype.UUID
	Memo     string
	PostedAt pgtype.Timestamptz
	Rank     float32
}

func (q *Queries) SearchFinanceEntries(ctx context.Context, arg SearchFinanceEntriesParams) ([]SearchFinanceEntriesRow, error) {
	rows, err := q.db.Query(ctx, searchFinanceEntries, arg.WebsearchToTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchFinanceEntriesRow
	for rows.Next() {
		var i SearchFinanceEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Memo,
			&i.PostedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
