// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeTask = `-- name: CompleteTask :execrows
UPDATE tasks SET status = 'done', done_at = now()
WHERE id = $1 AND status = 'open'
`

func (q *Queries) CompleteTask(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, completeTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (tenant_id, title, note, due_on, assignee, created_by)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, tenant_id, title, note, status, due_on, assignee, created_by, created_at, done_at, search
`

type CreateTaskParams struct {
	TenantID  pgtype.UUID
	Title     string
	Note      string
	DueOn     pgtype.Date
	Assignee  string
	CreatedBy string
}

// Запросы модуля «Задачи». Границу tenant'ов проводит RLS.
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.TenantID,
		arg.Title,
		arg.Note,
		arg.DueOn,
		arg.Assignee,
		arg.CreatedBy,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Note,
		&i.Status,
		&i.DueOn,
		&i.Assignee,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DoneAt,
		&i.Search,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTask = `-- name: GetTask :one
SELECT id, tenant_id, title, note, status, due_on, assignee, created_by, created_at, done_at, search FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Note,
		&i.Status,
		&i.DueOn,
		&i.Assignee,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DoneAt,
		&i.Search,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, tenant_id, title, note, status, due_on, assignee, created_by, created_at, done_at, search FROM tasks
WHERE ($3::text IS NULL OR status = $3)
  AND ($4::text IS NULL OR assignee = $4)
  AND ($5::text IS NULL
       OR search @@ websearch_to_tsquery('russian', $5))
ORDER BY
  CASE WHEN $6::text = 'due'      THEN due_on END ASC NULLS LAST,
  CASE WHEN $6::text = 'due_desc' THEN due_on END DESC NULLS LAST,
  CASE WHEN $6::text = 'created'  THEN created_at END ASC,
  created_at DESC
LIMIT $1 OFFSET $2
`

type ListTasksParams struct {
	Limit    int32
	Offset   int32
	Status   *string
	Assignee *string
	Q        *string
	Sort     string
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Assignee,
		arg.Q,
		arg.Sort,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Note,
			&i.Status,
			&i.DueOn,
			&i.Assignee,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DoneAt,
			&i.Search,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
